apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hotrod
  name: hotrod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotrod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hotrod
    spec:
      containers:
      - args:
        - all
        env:
        - name: JAEGER_AGENT_HOST
          value: jaeger
        - name: JAEGER_AGENT_PORT
          value: "6831"
        image: jaegertracing/example-hotrod:latest
        name: hotrod
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
