apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  labels:
    app: zipkin
  name: "zipkin"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "zipkin"
    spec:
      containers:
      - env:
        - name: "STORAGE_PORT_9042_TCP_ADDR"
          value: "cassandra:9042"
        - name: "STORAGE_PORT_3306_TCP_ADDR"
          value: "zipkin-mysql:3307"
        - name: "STORAGE_TYPE"
          value: "cassandra3"
        - name: "TRANSPORT_TYPE"
          value: "http"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "openzipkin/zipkin:latest"
        name: "zipkin"
      tolerations:
        - key: "node2"
          operator: "Exists"
          effect: "NoSchedule"    
