apiVersion: v1
kind: Service
metadata:
  labels:
    app: zipkin
  name: zipkin
spec:
  type: NodePort
  ports:
  - name: "9411"
    port: 9411
    targetPort: 9411
  selector:
    app: zipkin
status:
  loadBalancer: {}
