apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: jaeger
  name: jaeger
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - image: jaegertracing/all-in-one:latest
        name: jaeger
        ports:
        - containerPort: 6831
          protocol: UDP
        - containerPort: 16686
        resources: {}
      restartPolicy: Always
status: {}
